title: [Stephen J. Snow]
onaltitle: Stephen Snow
description: 
  <br> <br>
  Welcome to my portfolio!
  <br> <br>
  I am an undergraduate student at <a href-"https://www.dal.ca/">Dalhousie University</a> in Halifax, NS and I will be graduating in May 2021, with a BSc in Psychology and minor in Health Studies.


theme: jekyll-theme-minimal
logo: headshot.png



github:
  is_project_page: false
