title: [Stephen J. Snow]
onaltitle: Stephen Snow
description: I am an undergraduate student at Dalhousie University in Halifax, NS and I will be graduating in May 2021, with a BSc in Psychology and minor in Health Studies. Under the direction of Dr. Tim Bardouille, I have spent time volunteering in Dalhousie's Biosignal Lab, which uses advanced imaging technologies to non-invasively study activity in the brain. My research interests lie primarily in the areas of neuroimaging techniques, neurological trauma and public health. Below are some samples of python code I have written for the analysis and visualization of these interests. Thanks for visiting!
theme: jekyll-theme-minimal
logo: headshot.png



github:
  is_project_page: false
